# Description:
#   Cards Against Humanity v0.1
#
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   card me|card 2|q card
#
# Author:
#   Jonny Campbell (@jonnycampbell)

questions = [
  "TSA guidelines now prohibit __________ on airplanes.",
  "It's a pity that kids these days are all getting involved with __________.",
  "In 1,000 years, when paper money is but a distant memory, __________ will be our currency.",
  "Major League Baseball has banned __________ for giving players an unfair advantage.",
  "What is Batman's guilty pleasure?",
  "Next from J.K. Rowling: Harry Potter and the Chamber of __________.",
  "I'm sorry, Professor, but I couldn't complete my homework because of __________.",
  "What did I bring back from Mexico?",
  "__________? There's an app for that.",
  "__________. Betcha can't have just one!",
  "What's my anti-drug?",
  "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on __________.",
  "In the new Disney Channel Original Movie, Hannah Montana struggles with __________ for the first time.",
  "What's my secret power?",
  "What's the new fad diet?",
  "What did Vin Diesel eat for dinner?",
  "When Pharaoh remained unmoved, Moses called down a Plague of __________.",
  "How am I maintaining my relationship status?",
  "What's the crustiest?",
  "In L.A. County Jail, word is you can trade 200 cigarettes for __________.",
  "After the earthquake, Sean Penn brought __________ to the people of Haiti.",
  "Instead of coal, Santa now gives the bad children __________.",
  "Life for American Indians was forever changed when the White Man introduced them to __________.",
  "What's Teach for America using to inspire inner city students to succeed?",
  "Maybe she's born with it. Maybe it's __________.",
  "In Michael Jackson's final moments, he thought about __________.",
  "White people like __________.",
  "Why do I hurt all over?",
  "A romantic, candlelit dinner would be incomplete without __________.",
  "What will I bring back in time to convince people that I am a powerful wizard?",
  "BILLY MAYS HERE FOR __________.",
  "The class field trip was completely ruined by __________.",
  "What's a girl's best friend?",
  "Dear Abby, I'm having some trouble with __________ and would like your advice.",
  "When I am President of the United States, I will create the Department of __________.",
  "What are my parents hiding from me?",
  "What never fails to liven up the party?",
  "What gets better with age?",
  "__________: Good to the last drop.",
  "I got 99 problems but __________ ain't one.",
  "__________. It's a trap!",
  "MTV's new reality show features eight washed-up celebrities living with __________.",
  "What would grandma find disturbing, yet oddly charming?",
  "What's the most emo?",
  "During sex, I like to think about __________.",
  "What ended my last relationship?",
  "What's that sound?",
  "__________. That's how I want to die.",
  "Why am I sticky?",
  "What's the next Happy Meal toy?",
  "What's there a ton of in heaven?",
  "I do not know with what weapons World War III will be fought, but World War IV will be fought with __________.",
  "What will always get you laid?",
  "__________: Kid-tested, mother-approved.",
  "Why can't I sleep at night?",
  "What's that smell?",
  "What helps Obama unwind?",
  "This is the way the world ends / This is the way the world ends / Not with a bang but with __________.",
  "Coming to Broadway this season, __________: The Musical.",
  "Anthropologists have recently discovered a primitive tribe that worships __________.",
  "But before I kill you, Mr. Bond, I must show you __________.",
  "Studies show that lab rats navigate mazes 50% faster after being exposed to __________.",
  "Next on ESPN2: The World Series of __________.",
  "When I am a billionaire, I shall erect a 50-foot statue to commemorate __________.",
  "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on __________.",
  "War! What is it good for?",
  "What gives me uncontrollable gas?",
  "What do old people smell like?",
  "What am I giving up for Lent?",
  "Alternative medicine is now embracing the curative powers of __________.",
  "What did the US airdrop to the children of Afghanistan?",
  "What does Dick Cheney prefer?",
  "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of __________.",
  "What don't you want to find in your Chinese food?",
  "I drink to forget __________.",
  "__________. High five, bro.",
  "He who controls __________ controls the world.",
  "The CIA now interrogates enemy agents by repeatedly subjecting them to __________.",
  "In Rome, there are whisperings that the Vatican has a secret room devoted to __________.",
  "Science will never explain the origin of __________.",
  "When all else fails, I can always masturbate to __________.",
  "I learned the hard way that you can't cheer up a grieving friend with __________.",
  "In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated __________.",
  "The socialist governments of Scandinavia have declared that access to __________ is a basic human right.",
  "In his new self-produced album, Kanye West raps over the sounds of __________.",
  "What's the gift that keeps on giving?",
  "This season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only __________ and his wits.",
  "When I pooped, what came out of my butt?",
  "In the distant future, historians will agree that __________ marked the beginning of America's decline.",
  "What has been making life difficult at the nudist colony?",
  "And I would have gotten away with it, too, if it hadn't been for __________.",
  "What brought the orgy to a grinding halt?",
  "__________. High five, bro.",
  "TSA guidelines now prohibit __________ on airplanes.",
  "It's a pity that kids these days are all getting involved with __________.",
  "In 1,000 years, when paper money is but a distant memory, __________ will be our currency.",
  "Major League Baseball has banned __________ for giving players an unfair advantage.",
  "What is Batman's guilty pleasure?",
  "Next from J.K. Rowling: Harry Potter and the Chamber of __________.",
  "I'm sorry, Professor, but I couldn't complete my homework because of __________.",
  "What did I bring back from Mexico?",
  "__________? There's an app for that.",
  "Betcha can't have just one!",
  "What's my anti-drug?",
  "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on __________.",
  "In the new Disney Channel Original Movie, Hannah Montana struggles with __________ for the first time.",
  "What's my secret power?",
  "What's the new fad diet?",
  "What did Vin Diesel eat for dinner?",
  "When Pharaoh remained unmoved, Moses called down a Plague of __________.",
  "How am I maintaining my relationship status?",
  "What's the crustiest?",
  "When I'm in prison, I'll have __________ smuggled in.",
  "After Hurricane Katrina, Sean Penn brought __________ to the people of New Orleans.",
  "Instead of coal, Santa now gives the bad children __________.",
  "Life was difficult for cavemen before __________.",
  "What's Teach for America using to inspire inner city students to succeed?",
  "Who stole the cookies from the cookie jar?",
  "In Michael Jackson's final moments, he thought about __________.",
  "White people like __________.",
  "Why do I hurt all over?",
  "A romantic candlelit dinner would be incomplete without __________.",
  "What will I bring back in time to convince people that I am a powerful wizard?",
  "BILLY MAYS HERE FOR __________.",
  "The class field trip was completely ruined by __________.",
  "What's a girl's best friend?",
  "I wish I hadn't lost the instruction manual for __________.",
  "When I am President of the United States, I will create the Department of __________.",
  "What are my parents hiding from me?",
  "What never fails to liven up the party?",
  "What gets better with age?",
  "__________: good to the last drop.",
  "I got 99 problems but __________ ain't one.",
  "It's a trap!",
  "MTV's new reality show features eight washed-up celebrities living with __________.",
  "What would grandma find disturbing, yet oddly charming?",
  "What's the most emo?",
  "During sex, I like to think about __________.",
  "What ended my last relationship?",
  "What's that sound?",
  "__________. That's how I want to die.",
  "Why am I sticky?",
  "What's the next Happy Meal® toy?",
  "What's there a ton of in heaven?",
  "I do not know with what weapons World War III will be fought, but World War IV will be fought with __________.",
  "What will always get you laid?",
  "__________: kid tested, mother approved.",
  "Why can't I sleep at night?",
  "What's that smell?",
  "What helps Obama unwind?",
  "This is the way the world ends \ This is the way the world ends \ Not with a bang but with __________.",
  "Coming to Broadway this season, __________: The Musical.",
  "Anthropologists have recently discovered a primitive tribe that worships __________.",
  "But before I kill you, Mr. Bond, I must show you __________.",
  "Studies show that lab rats navigate mazes 50% faster after being exposed to __________.",
  "Due to a PR fiasco, Walmart no longer offers __________.",
  "When I am a billionaire, I shall erect a 50-foot statue to commemorate __________.",
  "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on __________.",
  "War! What is it good for?",
  "What gives me uncontrollable gas?",
  "What do old people smell like?",
  "Sorry everyone, I just __________.",
  "Alternative medicine is now embracing the curative powers of __________.",
  "The U.S. has begun airdropping __________ to the children of Afghanistan.",
  "What does Dick Cheney prefer?",
  "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of __________.",
  "What don't you want to find in your Chinese food?",
  "I drink to forget __________.",
  "That's right, I killed __________. How, you ask? __________.",
  "And the Academy Award for __________ goes to __________.",
  "For my next trick, I will pull __________ out of __________.",
  "In his new summer comedy, Rob Schneider is __________ trapped in the body of __________.",
  "When I was tripping on acid, __________ turned into __________.",
  "__________ is a slippery slope that leads to __________.",
  "In a world ravaged by __________, our only solace is __________.",
  "In M. Night Shyamalan's new movie, Bruce Willis discovers that __________ had really been __________ all along.",
  "I never truly understood __________ until I encountered __________.",
  "Rumor has it that Vladimir Putin's favorite dish is __________ stuffed with __________.",
  "Lifetime® presents __________, the story of __________.",
  "What's the next superhero/sidekick duo?"
]
answers = [
  "\"Tweeting.\"",
  "72 virgins.",
  "8 oz. of sweet Mexican black-tar heroin.",
  "A 55-gallon drum of lube.",
  "A Bop It.",
  "A Bop It™.",
  "A Burmese tiger pit.",
  "A Christmas stocking full of coleslaw.",
  "A Gypsy curse.",
  "A Hungry-Man Frozen Christmas Dinner for One.",
  "A PowerPoint presentation.",
  "A Super Soaker full of cat pee.",
  "A Super Soaker™ full of cat pee.",
  "A bag of magic beans.",
  "A balanced breakfast.",
  "A beached whale.",
  "A big black dick.",
  "A big hoopla about nothing.",
  "A bigger, blacker dick.",
  "A black male in his early 20s, last seen wearing a hoodie.",
  "A bleached asshole.",
  "A bloody pacifier.",
  "A boo-boo.",
  "A botched circumcision.",
  "A brain tumor.",
  "A can of whoop-ass.",
  "A cat video so cute that your eyes roll back and your spine slides out of your anus.",
  "A clandestine butt scratch.",
  "A cooler full of organs.",
  "A cop who is also a dog.",
  "A crappy little hand.",
  "A death ray.",
  "A defective condom.",
  "A disappointing birthday party.",
  "A dollop of sour cream.",
  "A drive-by shooting.",
  "A falcon with a cap on its head.",
  "A fetus.",
  "A foul mouth.",
  "A gassy antelope.",
  "A gentle caress of the inner thigh.",
  "A good sniff.",
  "A greased-up Matthew McConaughey.",
  "A homoerotic volleyball montage.",
  "A hot mess.",
  "A lamprey swimming up the toilet and latching onto your taint.",
  "A lifetime of sadness.",
  "A look-see.",
  "A low standard of living.",
  "A magic hippie love cloud.",
  "A man in yoga pants with a ponytail and feather earrings.",
  "A mating display.",
  "A micropenis.",
  "A middle-aged man on roller skates.",
  "A mime having a stroke.",
  "A moment of silence.",
  "A monkey smoking a cigar.",
  "A mopey zoo lion.",
  "A murder most foul.",
  "A nuanced critique.",
  "A passionate Latino lover.",
  "A pile of squirming bodies.",
  "A pinata full of scorpions.",
  "A really cool hat.",
  "A rival dojo",
  "A rival dojo.",
  "A robust mongoloid.",
  "A sad fat dragon with no friends.",
  "A sad handjob.",
  "A salty surprise.",
  "A sassy black woman.",
  "A sausage festival.",
  "A sea of troubles.",
  "A slightly shittier parallel universe.",
  "A snapping turtle biting the tip of your penis.",
  "A soulful rendition of “Ol' Man River.”",
  "A spontaneous conga line.",
  "A squadron of moles wearing aviator goggles.",
  "A stray pube.",
  "A surprising amount of hair.",
  "A sweaty, panting leather daddy.",
  "A sweet spaceship.",
  "A thermonuclear detonation.",
  "A time travel paradox.",
  "A tiny horse.",
  "A toxic family environment.",
  "A vagina that leads to another dimension.",
  "A visually arresting turtleneck.",
  "A web of lies.",
  "A windmill full of corpses.",
  "A woman scorned.",
  "A zesty breakfast burrito.",
  "AIDS.",
  "AXE Body Spray.",
  "AXE body spray.",
  "Aaron Burr.",
  "Active listening.",
  "Actually getting shot, for real.",
  "Actually taking candy from a baby.",
  "Adderall.",
  "Adderall™.",
  "African children.",
  "Agriculture.",
  "Alcoholism.",
  "All my friends dying.",
  "All of this blood.",
  "All-you-can-eat shrimp for $4.99.",
  "Altar boys.",
  "American Gladiators.",
  "Amputees.",
  "An M. Night Shyamalan plot twist.",
  "An Oedipus complex.",
  "An all-midget production of Shakespeare’s Richard III.",
  "An army of skeletons.",
  "An ass disaster.",
  "An asymmetric boob job.",
  "An erection that lasts longer than four hours.",
  "An erection that lasts more than four hours.",
  "An ether-soaked rag.",
  "An honest cop with nothing left to lose.",
  "An icepick lobotomy.",
  "An unhinged ferris wheel rolling toward the sea.",
  "An unstoppable wave of fire ants.",
  "Anal beads.",
  "Another goddamn vampire movie.",
  "Another shitty year.",
  "Another shop of morphine.",
  "Apologizing.",
  "Appreciative snapping.",
  "Arnold Schwarzenegger.",
  "Asians who aren't good at math.",
  "Assless chaps.",
  "Attitude.",
  "Auschwitz.",
  "Authentic Mexican cuisine.",
  "Autocannibalism.",
  "BATMAN!!!",
  "Balls.",
  "Barack Obama.",
  "Basic human decency.",
  "Beating your wives.",
  "Beefin' over turf.",
  "Bees?",
  "Being a bust adult with many important things to do.",
  "Being a busy adult with many important things to do.",
  "Being a dick to children.",
  "Being a dinosaur.",
  "Being a motherfucking sorcerer.",
  "Being awesome at sex.",
  "Being fabulous.",
  "Being marginalized.",
  "Being on fire.",
  "Being rich.",
  "Bill Clinton, naked on a bearskin rug with a saxophone.",
  "Bill Nye the Science Guy.",
  "Bingeing and purging.",
  "Bitches.",
  "Black people.",
  "Bling.",
  "Blood farts.",
  "Blowing some dudes in an alley.",
  "Booby-trapping the house to foil burglars.",
  "Boogers.",
  "Boris the Soviet Love Hammer.",
  "Bosnian chicken farmers.",
  "Breaking out into song and dance.",
  "Britney Spears at 55.",
  "Bullshit.",
  "Buying the right pants to be cool.",
  "Cards Against Humanity.",
  "Carnies.",
  "Catapults.",
  "Catastrophic Urethral Trauma.",
  "Centaurs.",
  "Chainsaws for hands.",
  "Charisma.",
  "Cheating in the Special Olympics.",
  "Child abuse.",
  "Child beauty pageants.",
  "Children on leashes.",
  "Chivalry.",
  "Christopher Walken.",
  "Chugging a lava lamp.",
  "Chutzpah.",
  "Civilian casualties.",
  "Clams.",
  "Classist Undertones.",
  "Classist undertones.",
  "Clearing a bloody path through Walmart with a scimitar.",
  "Coat hanger abortions.",
  "Cock.",
  "Cockfights.",
  "College.",
  "Concealing a boner.",
  "Consultants.",
  "Copping a feel.",
  "Coughing into a vagina.",
  "Count Chocula.",
  "Crippling debt.",
  "Crying into the pages of Sylvia Plath.",
  "Crystal meth.",
  "Cuddling.",
  "Customer service representatives.",
  "Cybernetic enhancements.",
  "Daddy issues.",
  "Daddy's belt.",
  "Dancing with a broom.",
  "Darth Vader.",
  "Date rape.",
  "Dead babies.",
  "Dead parents.",
  "Death by Steven Seagal.",
  "Deflowering the princess.",
  "Demonic possession.",
  "Dental dams.",
  "Dick Cheney.",
  "Dick fingers.",
  "Dining with cardboard cutouts of the cast of “Friends.”",
  "Disco fever.",
  "Doin' it in the butt.",
  "Doing the right thing.",
  "Domino's Oreo Dessert Pizza.",
  "Domino's™ Oreo™ Dessert Pizza.",
  "Dorito breath.",
  "Double penetration.",
  "Drinking alone.",
  "Drinking ten 5-hour ENERGYs to get fifty continuous hours of energy.",
  "Dropping a chandelier on your enemies and riding the rope up.",
  "Dry heaving.",
  "Dwarf tossing.",
  "Dying alone and in pain.",
  "Dying of dysentery.",
  "Dying.",
  "Eating Tom Selleck’s mustache to gain his powers.",
  "Eating all of the cookies before the AIDS bake-sale.",
  "Eating an albino.",
  "Eating an entire snowman.",
  "Eating the last known Bison.",
  "Eating the last known bison.",
  "Edible underpants.",
  "Elderly Japanese men.",
  "Elf cum.",
  "Embryonic stem cells.",
  "Emotions.",
  "Enormous Scandinavian women.",
  "Erectile dysfunction.",
  "Estrogen.",
  "Ethnic cleansing.",
  "Eugenics.",
  "Euphoria by Calvin Klein.",
  "Euphoria™ by Calvin Klein.",
  "Exactly what you'd expect.",
  "Exchanging pleasantries.",
  "Existing.",
  "Expecting a burp and vomiting on the floor.",
  "Explosions.",
  "Fabricating statistics.",
  "Famine.",
  "Fancy Feast.",
  "Farting and walking away.",
  "Fear itself.",
  "Feeding Rosie O'Donnell.",
  "Fetal alcohol syndrome.",
  "Fiery poops.",
  "Figgy pudding.",
  "Filling every orifice with butterscotch pudding.",
  "Finding Waldo.",
  "Finding a skeleton.",
  "Finger painting.",
  "Fingering.",
  "Firing a rifle into the air while balls deep in a squealing hog.",
  "Fisting.",
  "Five-Dollar Footlongs.",
  "Five-Dollar Footlongs™.",
  "Flash flooding.",
  "Flesh-eating bacteria.",
  "Flightless birds.",
  "Flying robots that kill people.",
  "Flying sex snakes.",
  "Foreskin.",
  "Forgetting the Alamo.",
  "Former President George W. Bush.",
  "Free samples.",
  "Friction.",
  "Friendly fire.",
  "Friends who eat all the snacks.",
  "Friends with benefits.",
  "Frolicking.",
  "Fuck Mountain.",
  "Fucking up “Silent Night” in front of 300 parents.",
  "Full frontal nudity.",
  "Gandalf.",
  "Gandhi.",
  "Gay aliens.",
  "Geese.",
  "Genetically engineered super-soldiers.",
  "Genghis Khan.",
  "Genital piercings.",
  "George Clooney's musk.",
  "German dungeon porn.",
  "Getting abducted by Peter Pan.",
  "Getting drunk on mouthwash.",
  "Getting hilariously gang-banged by the Blue Man Group.",
  "Getting in her pants, politely.",
  "Getting naked and watching Nickelodeon.",
  "Getting really high.",
  "Getting so angry that you pop a boner.",
  "Getting your dick stuck in a Chinese finger trap with another dick.",
  "Ghandi.",
  "Ghosts.",
  "Gift-wrapping a live hamster.",
  "Girls that always be textin’.",
  "Giving 110 percent.",
  "Giving 110%.",
  "Gladiatorial combat.",
  "Gladitorial combat.",
  "Glenn Beck being harried by a swarm of buzzards.",
  "Glenn Beck catching his scrotum on a curtain hook.",
  "Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts.",
  "Global warming.",
  "Gloryholes.",
  "GoGurt.",
  "Goats eating cans.",
  "Goblins.",
  "God.",
  "Going around punching people.",
  "Golden showers.",
  "Good grammar.",
  "Grandma.",
  "Grandpa's ashes.",
  "Graphic violence, adult language and some sexual content.",
  "Grave robbing.",
  "Guys who don't call.",
  "Half-assed foreplay.",
  "Harry Potter erotica.",
  "Having sex on top of a pizza.",
  "Having shotguns for legs.",
  "Heartwarming orphans.",
  "Her Royal Highness, Queen Elizabeth II.",
  "Heteronormativity.",
  "Hillary Clinton's death stare.",
  "Hipsters.",
  "Historical revisionism.",
  "Historically black colleges.",
  "Home video of Oprah sobbing into a Lean Cuisine.",
  "Homeless people.",
  "Hope.",
  "Hormone injections.",
  "Horrifying laser hair removal accidents.",
  "Horse meat.",
  "Hot Cheese.",
  "Hot Pockets.",
  "Hot cheese.",
  "Hot people.",
  "Hulk Hogan.",
  "Hurricane Katrina.",
  "Immaculate conception.",
  "Inappropriate yodeling.",
  "Incest.",
  "Indescribable loneliness.",
  "Insatiable bloodlust.",
  "Intelligent design.",
  "Intimacy problems.",
  "Italians.",
  "Jafar.",
  "Jean-Claude Van Damme.",
  "Jeff Goldblum.",
  "Jerking off into a pool of children's tears.",
  "Jew-fros.",
  "Jewish fraternities.",
  "Jibber-jabber.",
  "John Wilkes Booth.",
  "Judge Judy.",
  "Jumping out at people.",
  "Just the tip.",
  "Justin Bieber.",
  "Kamikaze pilots.",
  "Kanye West.",
  "Keanu Reaves.",
  "Keanu Reeves.",
  "Keg stands.",
  "Kids with ass cancer.",
  "Kim Jong-il.",
  "Kim-Jong-il.",
  "Krampus, the Austrian Christmas Monster.",
  "Lactation.",
  "Lady Gaga.",
  "Lance Armstrong's missing testicle.",
  "Land mines.",
  "Laying an egg.",
  "Leaving an awkward voicemail.",
  "Leprosy.",
  "Letting everyone down.",
  "Leveling up.",
  "Licking things to claim them as your own.",
  "Literally eating shit.",
  "Living in a trashcan.",
  "Lockjaw.",
  "Loki, the trickster god.",
  "Loose lips.",
  "Lumberjack fantasies.",
  "Lunchables.",
  "Lunchables™.",
  "Mad hacky-sack skills.",
  "Making a friend.",
  "Making a pouty face.",
  "Making the penises kiss.",
  "Mall Santa.",
  "Man meat.",
  "Masturbation.",
  "Mathletes.",
  "Me time.",
  "Me.",
  "MechaHitler.",
  "Media coverage.",
  "Medieval Times Dinner & Tournament.",
  "Medieval Times Dinner and Tournament.",
  "Men.",
  "Menstruation.",
  "Michael Jackson.",
  "Michelle Obama's arms.",
  "Mild autism.",
  "Mooing.",
  "Moral ambiguity.",
  "Morgan Freeman's voice.",
  "Mouth herpes.",
  "Mr. Clean, right behind you.",
  "Mufasa’s death scene.",
  "Muhammad (Praise Be Unto Him).",
  "Multiple stab wounds.",
  "Mutually-assured destruction.",
  "My collection of high-tech sex toys.",
  "My first kill.",
  "My genitals.",
  "My hot cousin.",
  "My humps.",
  "My inner demons.",
  "My machete.",
  "My manservant, Claude.",
  "My relationship status.",
  "My sex life.",
  "My soul.",
  "My vagina.",
  "Natalie Portman.",
  "Natural male enhancement.",
  "Natural selection.",
  "Nazis.",
  "Necrophilia.",
  "Neil Patrick Harris.",
  "New Age music.",
  "Nickelback.",
  "Nicolas Cage.",
  "Nipple blades.",
  "Nocturnal emissions.",
  "Not contributing to society in any meaningful way.",
  "Not giving a shit about the Third World.",
  "Not having sex.",
  "Not reciprocating oral sex.",
  "Nothing.",
  "Nubile slave boys.",
  "Nublile slave boys.",
  "Nunchuck moves.",
  "Obesity.",
  "Object permanence.",
  "Old-people smell.",
  "Ominous background music.",
  "One Ring to rule them all.",
  "One thousand Slim Jims.",
  "Oompa-Loompas.",
  "Opposable thumbs.",
  "Overcompensation.",
  "Overpowering your father.",
  "Oversized lollipops.",
  "Pabst Blue Ribbon.",
  "Pac-Man uncontrollably guzzling cum.",
  "Panda sex.",
  "Panty raids.",
  "Parting the Red Sea.",
  "Party poopers.",
  "Passable transvestites.",
  "Passing a kidney stone.",
  "Passive-aggressive Post-it notes.",
  "Pedophiles.",
  "Peeing a little bit.",
  "Penis envy.",
  "Picking up girls at the abortion clinic.",
  "Pictures of boobs.",
  "Pistol-whipping a hostage.",
  "Pixelated bukkake.",
  "Police brutality.",
  "Pooping back and forth. Forever.",
  "Poor life choices.",
  "Poor people.",
  "Poorly-timed Holocaust jokes.",
  "Porn stars.",
  "Powerful thighs.",
  "Prancing.",
  "Praying the gay away.",
  "Preteens.",
  "Pretending to be happy.",
  "Pretending to care.",
  "Pretty Pretty Princess Dress-Up Board Game.",
  "Pterodactyl eggs.",
  "Puberty.",
  "Public ridicule.",
  "Pulling out,",
  "Pulling out.",
  "Pumping out a baby every nine months.",
  "Puppies!",
  "Putting an entire peanut buter and jelly sandwich into the VCR.",
  "Queefing.",
  "Quiche.",
  "Quivering jowls.",
  "Racially-biased SAT questions.",
  "Racism.",
  "Raping and pillaging.",
  "Raptor attacks.",
  "Re-gifting.",
  "Repression,.",
  "Repression.",
  "Republicans.",
  "Revenge fucking.",
  "Reverse cowgirl.",
  "Riding off into the sunset.",
  "Ripping into a man's chest and pulling out his still-beating heart.",
  "Rising from the grave.",
  "Road head.",
  "Robert Downey, Jr.",
  "RoboCop.",
  "Roland the Farter, flatulist to the king.",
  "Ronald Reagan.",
  "Roofies.",
  "Running naked through a mall, pissing and shitting everywhere.",
  "Ryan Gosling riding in on a white horse.",
  "Same-sex ice dancing.",
  "Samuel L. Jackson.",
  "Santa Claus.",
  "Santa's heavy sack.",
  "Sarah Palin.",
  "Saxophone solos.",
  "Scalping.",
  "Science.",
  "Scientology,",
  "Scientology.",
  "Screaming like a maniac.",
  "Scrotal frostbite.",
  "Scrotum tickling.",
  "Scrubbing under the folds.",
  "Sean Connery.",
  "Sean Penn.",
  "Seduction.",
  "Self-flagellation.",
  "Self-loathing.",
  "Seppuku.",
  "Serfdom.",
  "Several intertwining love stories featuring Hugh Grant.",
  "Sexting.",
  "Sexual humiliation.",
  "Sexual tension.",
  "Sexy Siamese twins.",
  "Sexy pillow fights.",
  "Sexy siamese twins.",
  "Shaft.",
  "Shapeshifters.",
  "Shaquille O'Neal's acting career.",
  "Sharing needles.",
  "Shutting the fuck up.",
  "Skeletor.",
  "Slapping a racist old lady.",
  "Slow motion.",
  "Smallpox blankets.",
  "Smegma.",
  "Sneezing, farting, and coming at the same time. ",
  "Sniffing glue.",
  "Socks.",
  "Soiling oneself.",
  "Some douche with an acoustic guitar.",
  "Some kind of bird-man.",
  "Some really fucked-up shit.",
  "Soup that is too hot.",
  "Space Jam on VHS.",
  "Space muffins.",
  "Special musical guest, Cher.",
  "Spectacular abs.",
  "Spending lots of money.",
  "Sperm whales.",
  "Spontaneous human combustion.",
  "Spring break!",
  "Statistically validated stereotypes.",
  "Stephen Hawking talking dirty.",
  "Stifling a giggle at the mention of Hutus and Tutsis.",
  "Stranger danger.",
  "Subduing a grizzly bear and making her your wife.",
  "Sudden Poop Explosion Disease.",
  "Suicidal thoughts.",
  "Sunshine and rainbows.",
  "Surprise sex!",
  "Survivor's guilt.",
  "Sweet, sweet vengeance.",
  "Swiftly achieving orgasm.",
  "Switching to Geico.",
  "Swooping.",
  "Take-backsies.",
  "Taking a man's eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes.",
  "Taking down Santa with a surface-to-air missiles.",
  "Taking off your shirt.",
  "Tangled Slinkys.",
  "Tasteful sideboob.",
  "Teaching a robot to love.",
  "Team-building exercises.",
  "Teenage pregnancy.",
  "Tentacle porn.",
  "Testicular torsion.",
  "That ass.",
  "That thing that electrocutes your abs.",
  "The American Dream.",
  "The Amish.",
  "The Big Bang.",
  "The Blood of Christ.",
  "The Care Bear Stare.",
  "The Chinese gymnastics team.",
  "The Dance of the Sugar Plum Fairy.",
  "The Donald Trump Seal of Approval.",
  "The Donald Trump Seal of Approval™.",
  "The Fanta girls.",
  "The Force.",
  "The Google.",
  "The Gulags.",
  "The Hamburglar.",
  "The Harlem Globetrotters.",
  "The Holy Bible.",
  "The Hustle.",
  "The Jews.",
  "The KKK.",
  "The Kool-Aid Man.",
  "The Land of Chocolate.",
  "The Little Engine That Could.",
  "The Make-A-Wish Foundation.",
  "The Make-A-Wish foundation.",
  "The Pope.",
  "The Quesadilla Explosion Salad from Chili’s.",
  "The Rapture.",
  "The Rev. Dr. Martin Luther King, Jr.",
  "The South.",
  "The Star Wars Holiday Special.",
  "The Tempur-Pedic Swedish Sleep System.",
  "The Tempur-Pedic Swedish Sleep System™.",
  "The Three-Fifths Compromise.",
  "The Three-Fifths compromise.",
  "The Trail of Tears.",
  "The Ubermensch.",
  "The Underground Railroad.",
  "The Virginia Tech Massacre.",
  "The World of Warcraft.",
  "The boners of the elderly.",
  "The chronic.",
  "The clitoris.",
  "The corporations.",
  "The day the birds attacked.",
  "The economy.",
  "The entire Internet.",
  "The folly of man.",
  "The forbidden fruit.",
  "The four arms of Vishnu.",
  "The gays.",
  "The glass ceiling.",
  "The grey nutrient broth that sustains Mitt Romney.",
  "The hardworking Mexican.",
  "The harsh light of day.",
  "The heart of a child.",
  "The hiccups.",
  "The homosexual agenda.",
  "The human body.",
  "The inevitable heat death of the universe.",
  "The invisible hand.",
  "The mere concept of Applebee's.",
  "The milk man.",
  "The miracle of childbirth.",
  "The mixing of the races.",
  "The moist, demanding chasm of his mouth.",
  "The new Radiohead album.",
  "The placenta.",
  "The primal, ball-slapping sex your parents are having right now.",
  "The profoundly handicapped.",
  "The shambling corpse of Larry King.",
  "The systematic destruction of an entire people and their way of life.",
  "The taint; the grundle; the fleshy fun-bridge.",
  "The terrorists.",
  "The thin veneer of situational causality that underlies porn.",
  "The tiny calloused hands of the Chinese  children that made this card.",
  "The token minority.",
  "The true meaning of Christmas.",
  "The underground railroad.",
  "The violation of our most basic human rights.",
  "The way white people is.",
  "The Übermensch.",
  "Third base.",
  "Three months in the hole.",
  "Tiny nipples.",
  "Tom Cruise.",
  "Tongue.",
  "Toni Morrison's vagina.",
  "Too much hair gel.",
  "Tripping balls.",
  "Two midgets shitting into a bucket.",
  "Unfathomable stupidity.",
  "Unlimited soup, salad, and breadsticks.",
  "Upgrading homeless people to mobile hotspots.",
  "Uppercuts.",
  "Vehicular manslaughter.",
  "Velcro.",
  "Viagra.",
  "Vietnam flashbacks.",
  "Vigilante justice.",
  "Vigorous jazz hands.",
  "Vikings.",
  "Vomiting mid-blowjob.",
  "Waiting 'til marriage.",
  "Waiting ‘til marriage.",
  "Waking up half-naked in a Denny's parking lot.",
  "Warm, velvety muppet sex.",
  "Waterboarding.",
  "Weapons-grade plutonium.",
  "Wearing an octopus for a hat.",
  "Wearing underwear inside-out to avoid doing laundry.",
  "Whatever Kwanzaa is supposed to be about.",
  "When you fart and a little bit comes out.",
  "Whining like a little bitch.",
  "Whipping a disobedient slave.",
  "Whipping it out.",
  "White people.",
  "White privilege.",
  "Wifely duties.",
  "William Shatner.",
  "Winking at old people.",
  "Wiping her butt.",
  "Women in yogurt commercials.",
  "Women's suffrage.",
  "Words, words, words.",
  "World peace.",
  "YOU MUST CONSTRUCT ADDITIONAL PYLONS.",
  "Yeast.",
  "Zeus's sexual appetites.",
  "A Gypsy curse."
]

module.exports = (robot) ->
  robot.hear /(card me)/i, (msg) ->
    msg.send msg.random answers

  robot.hear /(card 2)/i, (msg) ->
    msg.send msg.random answers
    msg.send msg.random answers

  robot.hear /(card 3)/i, (msg) ->
    msg.send msg.random answers
    msg.send msg.random answers
    msg.send msg.random answers

  robot.hear /(q card)/i, (msg) ->
    msg.send msg.random questions
